### PR TITLE
Adding fields for more metadata [WIP]

### PR DESCRIPTION
**Pull request by pathumego**
@thinkholic I will keep editing this, please merge as you see fit

### CODE REVIEW

**Comment by kasunben** [comment]
@pathumego I actually prefer `id` over `uniqueID`, is there any explicit reason for naming it as `uniqueID`?

**Comment by pathumego** [comment]
type.world uses `uniqueID`

**Comment by kasunben** [comment]
ah okay. still using `uniqueID` is kinda odd since `id` is anyway unique for most cases.

If it's as `fontID` that's fine btw.

**Comment by pathumego** [comment]
closing in favor of #6

**Pull request closed without merging**
